type = "webpack"
account_id = "0123456789abcdef0123456789abcdef"
zone_id = "0123456789abcdef0123456789abcdef"
webpack_config = "webpack.config.js"

name = "url-shortener-dev"
route = "go-dev.example.com/*"
kv_namespaces = [
	 { binding = "REDIRECTS", id = "0123456789abcdef0123456789abcdef", preview_id = "0123456789abcdef0123456789abcdef"  }
]

[vars]
ENVIRONMENT = "dev"
GOOGLE_CLIENT_ID = "0123456789abcdef0123456789abcdef0123456789abc.apps.googleusercontent.com"

[env.production]
name = "url-shortener"
route = "go.example.com/*"
kv_namespaces = [
	 { binding = "REDIRECTS", id = "fedcba9876543210fedcba9876543210" }
]

[env.production.vars]
ENVIRONMENT = "production"
GOOGLE_CLIENT_ID = "0123456789abcdef0123456789abcdef0123456789abc.apps.googleusercontent.com"
